name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: "Lint: oxlint"
        run: pnpm lint:oxlint

      - name: "Lint: oxfmt"
        run: pnpm lint:oxfmt

      - name: "Lint: TypeScript"
        run: pnpm lint:tsc

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: "Tests: Unit"
        run: pnpm test:coverage

      - name: "Tests: E2E"
        run: pnpm test:e2e

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

  examples:
    name: Build examples
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install master
        run: pnpm install --frozen-lockfile

      - name: Install
        run: cd examples && pnpm install --frozen-lockfile

      - name: Build
        run: cd examples && pnpm build
